EventApplication/EventApplication/Models/Event.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EventApplication.Models
{
    public class Event : IValidatableObject
    {
        [Display(Name = "Event ID")]
        public virtual int EventId { get; set; }

        [Display(Name = "Event Type ID")]
        public virtual int EventTypeId { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        public virtual string Title { get; set; }

        public virtual string Desc { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Start Date")]
        public virtual DateTime StartDate { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "End Date")]
        public virtual DateTime EndDate { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        public virtual string City { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        public virtual string State { get; set; }

        [Display(Name = "Event Type")]
        public virtual EventType Type { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Organizer Name")]
        public virtual string OrgName { get; set; }

        [Display(Name = "Contact Info")]
        public virtual string OrgContact { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Max Tickets")]
        public virtual int TicMax { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Available Tickets")]
        public virtual int TicAvail { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Title.Length > 50)
            {
                yield return new ValidationResult("Title should not exceed 50 characters", new[] { "Title" });
            }

            if (Desc != null && Desc.Length > 150)
            {
                yield return new ValidationResult("Description should not exceed 150 characters", new[] { "Description" });
            }

            if (EndDate < StartDate)
            {
                yield return new ValidationResult("Event End Date cannot be less than Event Start Date", new[] { "EndDate" });
            }

            if (StartDate < DateTime.Now)
            {
                yield return new ValidationResult("Event Start Date cannot be in the past", new[] { "StartDate" });
            }

            if (EndDate < DateTime.Now)
            {
                yield return new ValidationResult("Event End Date cannot be in the past", new[] { "EndDate" });
            }

            if (TicMax < 1)
            {
                yield return new ValidationResult("Max Tickets cannot be less than 1", new[] { "TicketsMax" });
            }

            if (TicAvail < 1)
            {
                yield return new ValidationResult("Available Tickets cannot be less than 1", new[] { "TicketsAvailable" });
            }
        }
    }
}

EventApplication/EventApplication/Models/EventType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EventApplication.Models
{
    public class EventType : IValidatableObject
    {
        [Display(Name = "Event Type ID")]
        public virtual int EventTypeId { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Type")]
        public virtual string Title { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Title.Length > 50)
            {
                yield return new ValidationResult("Type should not exceed 50 characters", new[] { "Title" });
            }
        }
    }
}

EventApplication/EventApplication/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventApplication.Models;

namespace EventApplication.Controllers
{
    public class EventController : Controller
    {
        private EventApplicationDB db = new EventApplicationDB();
		
        public ActionResult Register(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        public ActionResult Find()
        {
            return View();
        }

        public ActionResult EventSearch(string eSearchString, string lSearchString)
        {
            var @event = GetEvents(eSearchString, lSearchString);
            if(@event.Count == 0)
            {
                return PartialView("_NothingFound");
            }
            else
            {
                return PartialView("_Find", @event);
            }
        }

        private List<Event> GetEvents(string eSearchString, string lSearchString)
        {
            return db.Events
                .Where(a => (a.Title.Contains(eSearchString) || a.Type.Title.Contains(eSearchString)) && (a.City.Contains(lSearchString) || a.State.Contains(lSearchString)) && a.StartDate > DateTime.Now)
                .OrderBy(a => a.StartDate)
                .ThenBy(a => a.Title)
                .ToList();
        }
		
        [Authorize]
        public ActionResult Index()
        {
            var events = db.Events.Include(a => a.Type);
            return View(events.ToList());
        }
		
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }
		
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.EventTypeId = new SelectList(db.EventTypes, "EventTypeId", "Title");
            return View();
        }
		
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "EventId,EventTypeId,Title,Desc,StartDate,EndDate,City,State,OrgName,OrgContact,TicMax,TicAvail")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EventTypeId = new SelectList(db.EventTypes, "EventTypeId", "Title", @event.EventTypeId);
            return View(@event);
        }
		
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            ViewBag.EventTypeId = new SelectList(db.EventTypes, "EventTypeId", "Title", @event.EventTypeId);
            return View(@event);
        }
		
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "EventId,EventTypeId,Title,Desc,StartDate,EndDate,City,State,OrgName,OrgContact,TicMax,TicAvail")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EventTypeId = new SelectList(db.EventTypes, "EventTypeId", "Title", @event.EventTypeId);
            return View(@event);
        }
		
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }
		
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventApplication/EventApplication/Controllers/EventTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventApplication.Models;

namespace EventApplication.Controllers
{
    [Authorize]
    public class EventTypeController : Controller
    {
        private EventApplicationDB db = new EventApplicationDB();
		
        public ActionResult Index()
        {
            return View(db.EventTypes.ToList());
        }
		
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventType eventType = db.EventTypes.Find(id);
            if (eventType == null)
            {
                return HttpNotFound();
            }
            return View(eventType);
        }
		
        public ActionResult Create()
        {
            return View();
        }
		
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TypeId,Title")] EventType eventType)
        {
            if (ModelState.IsValid)
            {
                db.EventTypes.Add(eventType);
                db.SaveChanges();
                return RedirectToAction("Create", "Event");
            }

            return View(eventType);
        }
		
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventType eventType = db.EventTypes.Find(id);
            if (eventType == null)
            {
                return HttpNotFound();
            }
            return View(eventType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TypeId,Title")] EventType eventType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eventType);
        }
		
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventType eventType = db.EventTypes.Find(id);
            if (eventType == null)
            {
                return HttpNotFound();
            }
            return View(eventType);
        }
		
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventType eventType = db.EventTypes.Find(id);
            db.EventTypes.Remove(eventType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventApplication/EventApplication/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventApplication.Models;

namespace EventApplication.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        EventApplicationDB db = new EventApplicationDB();
		
        public ActionResult Index()
        {
            OrderCart cart = OrderCart.GetCart(HttpContext);

            OrderCartViewModel vm = new OrderCartViewModel()
            {
                OrderItems = cart.GetCartItems()
            };

            return View(vm);
        }
		
        public ActionResult Summary(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order @order = db.Orders.Find(id);
            if (@order == null)
            {
                return HttpNotFound();
            }
            return View(@order);
        }
		
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order @order = db.Orders.Find(id);
            if (@order == null)
            {
                return HttpNotFound();
            }
            return View(@order);
        }
		
        public ActionResult AddToCart(int id, int count)
        {
            OrderCart cart = OrderCart.GetCart(HttpContext);
            var atcResult = cart.AddToCart(id, count);

            if ( atcResult == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return RedirectToAction("Summary", new { id =  atcResult });
        }
		
        [HttpPost]
        public ActionResult CancelOrder(int id)
        {
            OrderCart cart = OrderCart.GetCart(HttpContext);

            string newStatus = cart.CancelOrder(id);

            OrderCartRemoveViewModel vm = new OrderCartRemoveViewModel()
            {
                DeleteId = id,
                Status = newStatus
            };

            return Json(vm);
        }
    }
}

EventApplication/EventApplication/Views/Event/Create.cshtml
@model EventApplication.Models.Event

@{
    ViewBag.Title = "Organize Event";
}

<h2>Organize an Event</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.EventTypeId, "Event Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("EventTypeId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ActionLink("Create a new event type", "Create", "EventType")
            @Html.ValidationMessageFor(model => model.EventTypeId, "", new { @class = "text-danger" })
        </div>
        <div>

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { placeholder = "mm/dd/yyyy hh:mm:ss AM/PM", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { placeholder = "mm/dd/yyyy hh:mm:ss AM/PM", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrgName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrgName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrgName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrgContact, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrgContact, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrgContact, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TicMax, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TicMax, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TicMax, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TicAvail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TicAvail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TicAvail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventApplication/EventApplication/Views/Event/Delete.cshtml
@model EventApplication.Models.Event

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrgName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrgName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrgContact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrgContact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TicMax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicMax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TicAvail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicAvail)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EventApplication/EventApplication/Views/Event/Details.cshtml
@model EventApplication.Models.Event

@{
    ViewBag.Title = "Event Details";
}

<h2>Event</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrgName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrgName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrgContact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrgContact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TicMax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicMax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TicAvail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicAvail)
        </dd>

    </dl>
</div>
    <p>
    @if (Model.StartDate.Date > DateTime.Now && Model.TicAvail != 0 )
    {
        <text>@Html.ActionLink("Register", "Register", "Event", new { id = Model.EventId }, null) |</text>
    }
    @Html.ActionLink("Return Home", "Index", "Home")
    </p>

EventApplication/EventApplication/Views/Event/Find.cshtml
@{
    ViewBag.Title = "Find";
}
<br />
<div class="events">
    <h2>Find an Event</h2>

    @using (Ajax.BeginForm("EventSearch", "Event", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "GET",
        OnFailure = "searchFailed",
        UpdateTargetId = "searchresults"
    }))
    {
        <input type="text" name="eSearchString" placeholder="Event or Event Type" />
        <input type="text" name="lSearchString" placeholder="City or State" />
        <input type="submit" value="Search" class="btn btn-primary" />
    }
    <br />
    <div id="searchresults"></div>

</div>

@section Scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/App/Scripts.js"></script>
}

EventApplication/EventApplication/Views/Event/Index.cshtml
@model IEnumerable<EventApplication.Models.Event>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Type.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Desc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrgName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrgContact)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicMax)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicAvail)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Type.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Desc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrgName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrgContact)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TicMax)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TicAvail)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.EventId }) |
            @Html.ActionLink("Details", "Details", new { id = item.EventId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.EventId })
        </td>
    </tr>
}

</table>

EventApplication/EventApplication/Views/Event/Register.cshtml
@model EventApplication.Models.Event

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

<p>Sale ends on @Html.DisplayFor(model => model.StartDate.Month)/@Html.DisplayFor(model => model.StartDate.Day)/@Html.DisplayFor(model => model.StartDate.Year)</p>

<div id="error-message"></div>

<div class="row register-box">
    <div class="col-md-6">
        <strong>@Html.DisplayFor(model => model.Title)</strong>
    <br />
    FREE
</div>
    <div class="col-md-6">
        Number of Tickets<br />
        <select name="Count" id="Count" data-available="@Html.DisplayFor(model => model.TicketsAvailable)">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
        </select>
    </div>
</div><br />

@Html.ActionLink("Checkout", "AddToCart", "Order", new { @id = Model.EventId }, new { @id = "Checkout" })

@section Scripts{
    <script src="~/Scripts/App/Scripts.js"></script>
}

EventApplication/EventApplication/Views/Event/_Find.cshtml
@model IEnumerable<EventApplication.Models.Event>

<div id="searchresults">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Title, "Details", "Event", new { id = item.EventId }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
            </tr>
        }
    </table>
</div>